


<h1 class="title-1st">Voyagez où vous voulez...</h1>

<section class="sectionHome">
  <div class="homeLeft">
    <div>
      <h2>Découvrez-nous</h2>
      <p>Découvrez-en davantage sur notre équipe d'experts travaillant toujours au mieux pour vous proposer les meilleures destinations de voyages. <u> <a href="<?= $requestUrl ?>/description">Par ici</a></u> </p>
    </div>
  </div>

  <div class="homeMiddle">
    <div>
      <h2>Nos voyages</h2>
      <p>
        <p>Nous vous proposons toute un gamme de voyages adaptés à vos désirs:</p>
        <p>
        Des envies de visiter des planètes proches de la Terre ? C'est possible ! Nous pouvons vous proposer Mercure, Vénus ou encore Mars.<br>
        <u><a href="<?= $requestUrl ?>/destinations">C'est par ici !</a></u></p>
        <p>Vous préférez des voyages plus lointains ? Alors nos croisières sont faites pour vous !<br>
        Approchez-vous des géantes gazeuses de notre système solaire ou partez encore plus loin et admirez la galaxie d'Andromède. Une destination bien plus extrème vous est même proposée !<br>
        <u> <a href="<?= $requestUrl ?>/travels">C'est par ici !</a> </u>
        </p>
      </p>
    </div>
  </div>

  <div class="homeRight">
    <div>
      <h2>Identifiez-vous</h2>
      <p>Afin de reserver vos voyages, il est indispensable d'être <a href="<?= $requestUrl ?>/user/login"><u>connecté</u></a>.<br>
        Vous n'avez pas encore d'identifiants ? Alors <a href="<?= $requestUrl ?>/user"><u>inscrivez-vous</u></a> !
      </p>
    </div>
  </div>
</section>

<h1 class="title-2nd">...grâce à nos services</h1>
